"""initial schema

Revision ID: 5d15e43297ed
Revises: 
Create Date: 2026-05-16 01:54:42.113181

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5d15e43297ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('his_user', sa.String(length=64), nullable=True),
    sa.Column('his_host', sa.String(length=255), nullable=True),
    sa.Column('page_type', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=True),
    sa.Column('html_size', sa.Integer(), nullable=False),
    sa.Column('resources_upserted', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('auth_token_hint', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_his_user'), 'audit_log', ['his_user'], unique=False)
    op.create_index(op.f('ix_audit_log_patient_id'), 'audit_log', ['patient_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('authorization_codes',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('redirect_uri', sa.String(length=1024), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('patient_id', sa.String(length=255), nullable=True),
    sa.Column('code_challenge', sa.String(length=255), nullable=True),
    sa.Column('code_challenge_method', sa.String(length=16), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('fhir_resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('fhir_id', sa.String(length=255), nullable=False),
    sa.Column('version_id', sa.String(length=16), nullable=False),
    sa.Column('resource', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fhir_resources_fhir_id'), 'fhir_resources', ['fhir_id'], unique=False)
    op.create_index(op.f('ix_fhir_resources_resource_type'), 'fhir_resources', ['resource_type'], unique=False)
    op.create_table('oauth_clients',
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('redirect_uris', sa.JSON(), nullable=False),
    sa.Column('allowed_scopes', sa.JSON(), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('oauth_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=512), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('patient_id', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
    )
    op.create_table('patient_sync_state',
    sa.Column('patient_id', sa.String(length=255), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_log_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('sync_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_logs')
    op.drop_table('patient_sync_state')
    op.drop_table('oauth_tokens')
    op.drop_table('oauth_clients')
    op.drop_index(op.f('ix_fhir_resources_resource_type'), table_name='fhir_resources')
    op.drop_index(op.f('ix_fhir_resources_fhir_id'), table_name='fhir_resources')
    op.drop_table('fhir_resources')
    op.drop_table('authorization_codes')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_patient_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_his_user'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
