// Shared DOM-element registry. Lookups run at module load, so the
// popup bundle must execute after the DOM is parsed (it does — the
// entry runs at the end of popup.html). modeRadios stays a function
// because the radios are queried live (set may change post-load).

export const els = {
  modeRadios: () => document.querySelectorAll('input[name="sync-mode"]'),
  backendUrl: document.getElementById("backend-url"),
  syncApiKey: document.getElementById("sync-api-key"),
  smartAppUrl: document.getElementById("smart-app-url"),
  syncApiBtn: document.getElementById("sync-api-btn"),
  syncBlockedReason: document.getElementById("sync-blocked-reason"),
  apiSyncRange: document.getElementById("api-sync-range"),
  stopBtn: document.getElementById("stop-btn"),
  ovName: document.getElementById("ov-name"),
  ovBirthDate: document.getElementById("ov-birth-date"),
  ovGender: document.getElementById("ov-gender"),
  ovSaveBtn: document.getElementById("ov-save-btn"),
  ovClearBtn: document.getElementById("ov-clear-btn"),
  ovSummary: document.getElementById("override-summary"),
  patientOverrideDetails: document.getElementById("patient-override"),
  launchBtn: document.getElementById("launch-btn"),
  openSmartAppBtn: document.getElementById("open-smart-app-btn"),
  openSettingsBtn: document.getElementById("open-settings-btn"),
  settingsBackBtn: document.getElementById("settings-back-btn"),
  status: document.getElementById("status"),
  dashboardLink: document.getElementById("dashboard-link"),
  pendingBundle: document.getElementById("pending-bundle"),
  downloadBundleBtn: document.getElementById("download-bundle-btn"),
  clearBundleBtn: document.getElementById("clear-bundle-btn"),
  // bundleMeta legacy id removed in the panel-merge; filename+size now
  // live in dedicated #bundle-filename / #bundle-sizeage elements
  // below.
  connBanner: document.getElementById("conn-banner"),
  connSection: document.getElementById("conn-section"),
  connMini: document.getElementById("conn-mini"),
  connMsg: document.getElementById("conn-msg"),
  connRetryBtn: document.getElementById("conn-retry-btn"),
  connHelp: document.getElementById("conn-help"),
  dataStateSection: document.getElementById("data-state-section"),
  backendState: document.getElementById("backend-state"),
  localStateRow: document.getElementById("local-state-row"),
  localState: document.getElementById("local-state"),
  pushLocalBtn: document.getElementById("push-local-btn"),
  syncStatusHint: document.getElementById("sync-status-hint"),
  maskNameEnabled: document.getElementById("mask-name-enabled"),
  backendModeEnabled: document.getElementById("backend-mode-enabled"),
  openNhiSection: document.getElementById("open-nhi-section"),
  openNhiBtn: document.getElementById("open-nhi-btn"),
  nhiNeedsLoginSection: document.getElementById("nhi-needs-login-section"),
  nhiReloadBtn: document.getElementById("nhi-reload-btn"),
  loginOkSection: document.getElementById("login-ok-section"),
  wizardStepper: document.getElementById("wizard-stepper"),
  resultZone: document.getElementById("result-zone"),
  activePatient: document.getElementById("active-patient"),
  activePatientValue: document.getElementById("active-patient-value"),
  bundleMetaBlock: document.getElementById("bundle-meta-block"),
  bundleFilename: document.getElementById("bundle-filename"),
  bundleSizeage: document.getElementById("bundle-sizeage"),
};
